### ISSUE TITLE
Test with different JabRef version

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/literature#1]
BibTeX file created with:
**JabRef Version 2.10**

Tested with:
**JabRef Version 2.10**
**JabRef Version 4.2 (recent)**

**Comment by christian-rli** [comment]
Tested with jabref 3.8.2 (default package in ubuntu 18.04). Issue seems to be a non-issue and therefore i'm closing it. Once this repository is developed further and gets new features, this issue can be reopened.
