### ISSUE TITLE
Add literature (Databases)

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/literature#2]
1. Gather necessary information for databases/dataportals/repositories
1. Add to .bib
1. Add useful tags (e.g. DB, LOD, Open Data)

- [ ]   http://data.europa.eu/euodp/en/data/
- [ ] http://ec.europa.eu/
- [ ] http://energydata.info/
- [ ] http://energydata.uct.ac.za/
- [ ] http://enipedia.tudelft.nl/
- [ ] http://oep.iks.cs.ovgu.de/
- [ ] http://opengridmap.com/
- [ ] http://www.fao.org/faostat/en/#home
- [ ] http://www.smard.de
- [ ]   http://www.wri.org/publication/global-power-plant-database
- [ ] https://comtrade.un.org/
- [ ] https://data.worldbank.org/
- [ ] https://openei.org
- [ ] https://open-power-system-data.org/
- [ ]   https://www.dwd.de/DE/leistungen/testreferenzjahre/testreferenzjahre.html
- [ ] https://www.energidataservice.dk/
- [ ]   https://www.eumetsat.int/website/home/index.html
- [ ] https://www.openstreetmap.de/
- [ ] http://www.nachhaltigesbauen.de/
- [ ] http://www.oekobaudat.de/

**LOD:**
- [ ] Wikidata
- [ ] DBpedia
- [ ] European Data Portal
- [ ] EU Open Data Portal
- [ ] LinkedGeoData
- [ ] reegle.info

**Comment by klarareder** [comment]
As a   user I would like to get a list with links to other databases (e.g. FAO etc.), because I may   not know all of them yet.

**Comment by christian-rli** [comment]
"Add Linked Open Data sources to Literature" - User Feedback and part of the requirement specification.

RequirementSpecificationID=65

**Comment by klarareder** [comment]
ToDo: add to text: literature can only be added when logged in
I am not sure if this is a bug or a feature. But I am ok with feature

**Comment by klarareder** [comment]
ToDo: I do not get feedback when sending a bibtex-file, nothing happend. Do I have to wait until it is uploaded? Or did it not work?

**Comment by klarareder** [comment]
ToDo: make links visible (blue) and a clickable link

**Comment by klarareder** [comment]
ToDo: many '{' are at the wrong place. I changed one but nothing happend, do I need to wait? If yes change the rest later on

**Comment by klarareder** [comment]
We decided in a SzenarienDB project-meeting that the establishment of a proper literature database will be further reasearch. Within SzenarienDB we will offer the possilbilies to link Literature. This will be done as part of the re-design of the OEP. Hence, this isssue can be closed.
